export const Config = {
  SERVER_URL: __DEV__ ? process.env.EXPO_PUBLIC_SERVER_URL_DEV! : process.env.EXPO_PUBLIC_SERVER_URL_PROD!,
  GOOGLE_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID!,
  GOOGLE_IOS_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID!,
};
