name: EAS Update (Main Push)

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Create update + upload sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kori-front
          SENTRY_PROJECT: kori-front
          SENTRY_URL: https://sentry.io/
        run: |
          eas update --branch main --message "Update from GitHub Actions" --non-interactive
          npx sentry-expo-upload-sourcemaps dist